/// Vital preset JSON schema definitions.
///
/// A .vital preset file is a gzipped JSON file. This module defines
/// the Rust structs that map to the Vital preset schema.

use serde::{Deserialize, Serialize};

/// Top-level Vital preset structure.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VitalPreset {
    /// Preset name/author metadata
    #[serde(default)]
    pub preset_name: String,
    #[serde(default)]
    pub author: String,
    #[serde(default)]
    pub comments: String,

    /// Synthesis parameters — flattened key-value pairs.
    /// Vital uses a flat JSON structure with keys like:
    /// "osc_1_wave_frame", "filter_1_cutoff", "env_1_attack", etc.
    #[serde(flatten)]
    pub parameters: serde_json::Map<String, serde_json::Value>,
}

impl VitalPreset {
    /// Create a new preset with default values.
    pub fn new(name: &str) -> Self {
        Self {
            preset_name: name.to_string(),
            author: "Preset.gg".to_string(),
            comments: "Generated by Preset.gg AI".to_string(),
            parameters: serde_json::Map::new(),
        }
    }
}
