/// Vital preset JSON schema definitions and parameter allowlist.
///
/// A .vital preset file is a gzipped JSON file. This module defines:
/// - The Rust structs that map to the Vital preset schema
/// - The parameter allowlist: which keys Gemini is allowed to set, and their valid ranges
///
/// All parameter values are normalized 0.0–1.0 (per Spike C findings).
/// The Rust merge step maps to actual Vital ranges before writing the preset file.

use serde::{Deserialize, Serialize};

// ── Vital Preset Struct ───────────────────────────────────────────────────────

/// Top-level Vital preset structure.
///
/// Note: Vital's actual preset JSON format may wrap synthesis params under a
/// "settings" key. Once Nathan extracts a real Init.vital, update this struct
/// to match the actual schema if needed.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VitalPreset {
    /// Preset display name
    #[serde(default)]
    pub preset_name: String,
    /// Preset author
    #[serde(default)]
    pub author: String,
    /// Comments / description
    #[serde(default)]
    pub comments: String,
    /// Preset style tag (optional)
    #[serde(default)]
    pub preset_style: String,

    /// All synthesis parameters — flat key-value pairs merged from Init.vital.
    #[serde(flatten)]
    pub parameters: serde_json::Map<String, serde_json::Value>,
}

impl VitalPreset {
    pub fn new(name: &str) -> Self {
        Self {
            preset_name: name.to_string(),
            author: "Preset.gg".to_string(),
            comments: "Generated by Preset.gg — AI Audio-to-Preset".to_string(),
            preset_style: "".to_string(),
            parameters: serde_json::Map::new(),
        }
    }
}

// ── Parameter Allowlist ───────────────────────────────────────────────────────
//
// Format: (param_name, min, max)
// All values normalized 0.0–1.0 per spike decision.
// Gemini outputs 0–1; the merge step multiplies by (max–min) + min to get
// the actual Vital value.
//
// When Nathan extracts Init.vital, cross-reference these names against the
// real JSON keys and update any that differ.

pub const ALLOWED_PARAMS: &[(&str, f64, f64)] = &[
    // ── Oscillator 1 ──────────────────────────────────────────────────────────
    // wave_frame: 0=sine, 0.25=triangle, 0.5=sawtooth, 0.75=square, 1.0=noise
    ("osc_1_wave_frame",   0.0, 1.0),
    ("osc_1_level",        0.0, 1.0),
    ("osc_1_pan",          0.0, 1.0), // 0=hard left, 0.5=center, 1=hard right
    ("osc_1_tune",         0.0, 1.0), // 0.5=center (0 cents), 0=−100c, 1=+100c
    ("osc_1_transpose",    0.0, 1.0), // 0.5=0 semitones, normalized over ±24 semi
    ("osc_1_unison_voices",0.0, 1.0), // maps to 1–16 voices
    ("osc_1_unison_detune",0.0, 1.0),
    ("osc_1_phase",        0.0, 1.0),

    // ── Oscillator 2 ──────────────────────────────────────────────────────────
    ("osc_2_wave_frame",   0.0, 1.0),
    ("osc_2_level",        0.0, 1.0),
    ("osc_2_pan",          0.0, 1.0),
    ("osc_2_tune",         0.0, 1.0),
    ("osc_2_transpose",    0.0, 1.0),
    ("osc_2_unison_voices",0.0, 1.0),
    ("osc_2_unison_detune",0.0, 1.0),
    ("osc_2_phase",        0.0, 1.0),

    // ── Filter 1 ──────────────────────────────────────────────────────────────
    // cutoff: 0=fully closed (~20Hz), 1=fully open (~20kHz)
    ("filter_1_cutoff",    0.0, 1.0),
    ("filter_1_resonance", 0.0, 1.0),
    ("filter_1_drive",     0.0, 1.0),
    ("filter_1_blend",     0.0, 1.0), // 0=low-pass, 0.5=band-pass, 1=high-pass

    // ── Filter 2 ──────────────────────────────────────────────────────────────
    ("filter_2_cutoff",    0.0, 1.0),
    ("filter_2_resonance", 0.0, 1.0),
    ("filter_2_drive",     0.0, 1.0),
    ("filter_2_blend",     0.0, 1.0),

    // ── Envelope 1 (amplitude) ────────────────────────────────────────────────
    // attack/decay/release: 0=instant, 1=~4s
    ("env_1_attack",       0.0, 1.0),
    ("env_1_decay",        0.0, 1.0),
    ("env_1_sustain",      0.0, 1.0), // 0=silent, 1=full volume
    ("env_1_release",      0.0, 1.0),
    ("env_1_attack_power", 0.0, 1.0),
    ("env_1_decay_power",  0.0, 1.0),
    ("env_1_release_power",0.0, 1.0),

    // ── Envelope 2 (modulation) ───────────────────────────────────────────────
    ("env_2_attack",       0.0, 1.0),
    ("env_2_decay",        0.0, 1.0),
    ("env_2_sustain",      0.0, 1.0),
    ("env_2_release",      0.0, 1.0),

    // ── LFO 1 ─────────────────────────────────────────────────────────────────
    // frequency: 0=sub-Hz (very slow), 1=audio rate
    ("lfo_1_frequency",    0.0, 1.0),
    ("lfo_1_amount",       0.0, 1.0),
    ("lfo_1_phase",        0.0, 1.0),
    ("lfo_1_fade_time",    0.0, 1.0),
    ("lfo_1_delay_time",   0.0, 1.0),

    // ── LFO 2 ─────────────────────────────────────────────────────────────────
    ("lfo_2_frequency",    0.0, 1.0),
    ("lfo_2_amount",       0.0, 1.0),
    ("lfo_2_phase",        0.0, 1.0),

    // ── Effects ───────────────────────────────────────────────────────────────
    // reverb
    ("reverb_mix",         0.0, 1.0),
    ("reverb_decay_time",  0.0, 1.0),
    ("reverb_size",        0.0, 1.0),
    ("reverb_pre_low_cutoff",  0.0, 1.0),
    ("reverb_pre_high_cutoff", 0.0, 1.0),

    // delay
    ("delay_mix",          0.0, 1.0),
    ("delay_frequency",    0.0, 1.0), // synced to tempo
    ("delay_feedback",     0.0, 1.0),
    ("delay_filter_cutoff",0.0, 1.0),

    // chorus
    ("chorus_mix",         0.0, 1.0),
    ("chorus_amount",      0.0, 1.0),
    ("chorus_frequency",   0.0, 1.0),
    ("chorus_feedback",    0.0, 1.0),

    // distortion
    ("distortion_amount",  0.0, 1.0),
    ("distortion_mix",     0.0, 1.0),
    ("distortion_drive",   0.0, 1.0),

    // phaser
    ("phaser_mix",         0.0, 1.0),
    ("phaser_amount",      0.0, 1.0),
    ("phaser_frequency",   0.0, 1.0),
    ("phaser_feedback",    0.0, 1.0),

    // compressor
    ("compressor_mix",     0.0, 1.0),
    ("compressor_attack",  0.0, 1.0),
    ("compressor_release", 0.0, 1.0),
    ("compressor_ratio",   0.0, 1.0),
    ("compressor_threshold",0.0, 1.0),

    // ── Global ────────────────────────────────────────────────────────────────
    ("volume",             0.0, 1.0),
    ("velocity_track",     0.0, 1.0),
    ("pitch_range",        0.0, 1.0),
    ("stereo_routing",     0.0, 1.0),
];

/// Look up the valid (min, max) range for a parameter name.
/// Returns None if the key is not in the allowlist (should be dropped).
pub fn find_param_range(key: &str) -> Option<(f64, f64)> {
    ALLOWED_PARAMS
        .iter()
        .find(|(k, _, _)| *k == key)
        .map(|(_, min, max)| (*min, *max))
}
