/// Vital preset file generation and Gemini response merging.
///
/// Pipeline:
///   Gemini JSON output (normalized 0–1 values)
///   → look up each param in the mapping table
///   → convert from 0–1 to real Vital range
///   → merge into the real Init.vital template under ["settings"]
///   → auto-enable effects whose wet mix is nonzero
///   → set metadata at root level
///   → serialize → gzip → Vec<u8> (a valid .vital file)

use anyhow::{anyhow, Result};
use flate2::write::GzEncoder;
use flate2::Compression;
use serde_json::{json, Value};
use std::io::Write;

use super::schema::{find_mapping, EFFECT_AUTO_ON, INIT_TEMPLATE_JSON};

// ── Public API ────────────────────────────────────────────────────────────────

/// Merge Gemini's parameter output into the real Init.vital template,
/// then produce a gzipped .vital file as bytes.
pub fn merge_gemini_into_template(
    gemini_output: &Value,
    prompt: &str,
    track_title: Option<&str>,
) -> Result<Vec<u8>> {
    // 1. Parse the real Init.vital template.
    let mut template: Value = serde_json::from_str(INIT_TEMPLATE_JSON)
        .map_err(|e| anyhow!("Failed to parse Init.vital template: {}", e))?;

    // 2. Get mutable reference to the "settings" sub-object.
    let settings = template
        .get_mut("settings")
        .and_then(|s| s.as_object_mut())
        .ok_or_else(|| anyhow!("Init.vital template missing 'settings' object"))?;

    // 3. Get the Gemini output as an object.
    let gemini_params = gemini_output
        .as_object()
        .ok_or_else(|| anyhow!("Gemini output is not a JSON object"))?;

    let mut merged_count = 0usize;
    let mut dropped_count = 0usize;

    // 4. For each Gemini param, look up the mapping and convert.
    for (key, raw_value) in gemini_params {
        match find_mapping(key) {
            None => {
                dropped_count += 1;
                tracing::debug!("Dropping unknown Gemini param: {}", key);
            }
            Some(mapping) => {
                if let Some(v) = raw_value.as_f64() {
                    // Clamp Gemini's output to 0–1 first.
                    let clamped = v.clamp(0.0, 1.0);
                    // Convert to real Vital range.
                    let vital_value = (mapping.convert)(clamped);
                    settings.insert(mapping.vital_key.to_string(), json!(vital_value));
                    merged_count += 1;
                } else {
                    tracing::warn!(
                        "Gemini param {} has non-numeric value: {:?}",
                        key,
                        raw_value
                    );
                    dropped_count += 1;
                }
            }
        }
    }

    // 5. Auto-enable effects whose wet mix is nonzero.
    for (wet_key, on_key) in EFFECT_AUTO_ON {
        if let Some(wet_val) = settings.get(*wet_key).and_then(|v| v.as_f64()) {
            if wet_val > 0.001 {
                settings.insert(on_key.to_string(), json!(1.0));
            }
        }
    }

    // 6. If Gemini set osc_2_level > 0, enable osc 2.
    if let Some(osc2_level) = settings.get("osc_2_level").and_then(|v| v.as_f64()) {
        if osc2_level > 0.001 {
            settings.insert("osc_2_on".to_string(), json!(1.0));
        }
    }

    // 7. If Gemini set filter params, enable filter 1.
    if gemini_params.contains_key("filter_1_cutoff")
        || gemini_params.contains_key("filter_1_resonance")
        || gemini_params.contains_key("filter_1_drive")
        || gemini_params.contains_key("filter_1_blend")
    {
        settings.insert("filter_1_on".to_string(), json!(1.0));
    }

    tracing::info!(
        "Merged {} Gemini params into template ({} dropped as unknown/invalid)",
        merged_count,
        dropped_count
    );

    // 8. Set preset metadata at the ROOT level (not in settings).
    let preset_name = match track_title {
        Some(title) => format!("{} — {}", title, prompt),
        None => format!("AI Preset — {}", prompt),
    };
    let preset_name = if preset_name.len() > 64 {
        format!("{}...", &preset_name[..61])
    } else {
        preset_name
    };

    template["preset_name"] = json!(preset_name);
    template["author"] = json!("Preset.gg");
    template["comments"] = json!(format!("Generated by Preset.gg AI. Prompt: {}", prompt));

    // 9. Serialize and gzip.
    gzip_json(&template)
}

// ── Private helpers ───────────────────────────────────────────────────────────

/// Serialize a JSON value and gzip compress it.
fn gzip_json(value: &Value) -> Result<Vec<u8>> {
    let json_str = serde_json::to_string(value)
        .map_err(|e| anyhow!("JSON serialization failed: {}", e))?;

    let mut encoder = GzEncoder::new(Vec::new(), Compression::default());
    encoder
        .write_all(json_str.as_bytes())
        .map_err(|e| anyhow!("Gzip write failed: {}", e))?;
    let compressed = encoder
        .finish()
        .map_err(|e| anyhow!("Gzip finish failed: {}", e))?;

    tracing::info!(
        "Vital file: {} bytes JSON → {} bytes gzipped",
        json_str.len(),
        compressed.len()
    );

    Ok(compressed)
}
